### ISSUE TITLE
Windows compiling not working

### ISSUE THREAD

**Issue by jlxip** [vbooter/DDoS-Scripts#1]
All your source codes are for Linux, they use linux includes so I don't have any idea about how can I compile it using tcc.

**Comment by gertoe** [comment]
[this](http://repo.or.cz/w/tinycc.git/blob/refs/heads/mob:/win32/tcc-win32.txt#l78) may be helpful. Good luck, Windows-User.

**Comment by jlxip** [comment]
Couldn't make it work. But no worries, that was for a kind of """""project""""" that needed this feature running on Windows. Anyway, if I need to do these kinds of attacks, I'll use GNU/linux for sure. Greetings!
